# Generated by Django 3.0.6 on 2020-08-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_auto_20200828_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='La direcciòn'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tfno',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
    ]
